[package]
name = "subscriptemember"
version = "0.5.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[features]
default = []

[dependencies]
clippy = {version = "0.0.138", optional = true}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket = "0.2"
rocket_codegen = "0.2"
rocket_contrib = {version = "0.2", features = ["handlebars_templates", "json"]}
hyper = "0.10"
hyper-rustls = "0.6"
yup-oauth2 =  { git = "https://github.com/dermesser/yup-oauth2", rev="1247c35"} 
# yup-oauth2 = {version = "1.0"}
handlebars = "0.26"
chrono = {version = "0.3", features = ["serde"]}
chrono-tz = "0.3"
dotenv = "0.10"
diesel = {version = "0.13", features = ["sqlite"]}
diesel_codegen = {version = "0.13", features = ["sqlite"]}
r2d2 = "0.7"
r2d2-diesel = {version = "0.13"}
reqwest = "0.6"
nom = "3.0"
uuid = {version = "0.5", features = ["v4"]}
rayon = "0.7"
