[package]
name = "subscriptemember"
version = "0.1.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[features]
default = []

[dependencies]
clippy = {version = "0.0.110", optional = true}
yup-oauth2 = "1.0.1"
hyper = "0.9.14"
serde = "0.8.22"
serde_json = "0.8.4"
serde_derive = "0.8.22"
hyper_serde = "0.2.0"
rocket = "0.1.2"
rocket_codegen = "0.1.2"
handlebars = {version = "0.24.1", features = ["serde_type"]}
lazy_static = "0.2.2"
chrono = {version = "0.2.25", features = ["serde"]}
dotenv = "0.8.0"
diesel = {version = "0.9.1", features = ["sqlite"]}
diesel_codegen = {version = "0.9.0", features = ["sqlite"]}
r2d2 = "0.7.1"
r2d2-diesel = "0.9.0"