[package]
name = "subscriptemember"
version = "0.1.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[dependencies]
yup-oauth2 = "1.0.1"
hyper = "0.9.14"
serde = "0.8.21"
serde_json = "0.8.4"
rusqlite = "0.7.3"