[package]
name = "subscriptemember"
version = "0.5.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[features]
default = []

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
chrono-tz = "0.4"
clippy = {version = "0.0", optional = true}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = {version = "0.3", features = ["handlebars_templates", "json"]}
hyper = "0.10.2"
tokio-core = "0.1"
hyper-rustls = "0.6.1"
#yup-oauth2 =  { git = "https://github.com/dermesser/yup-oauth2", rev="8e7060b041fb28c802190206897c4a5d9d0aaf17"} 
yup-oauth2 = {version = "1.0"}
handlebars = "0.29"
dotenv = "0.10"
diesel = {version = "0.99", features = ["sqlite"]}
r2d2 = "0.8"
r2d2-diesel = {version = "0.99"}
reqwest = "0.6"
nom = "3.0"
uuid = {version = "0.5", features = ["v4"]}
rayon = "0.9"
ws = "0.7.3"         # Lightweight, event-driven WebSockets for Rust.


