[package]
name = "subscriptemember"
version = "0.1.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[features]
default = []

[dependencies]
clippy = {version = "0.0.112", optional = true}
serde = "0.9.5"
serde_json = "0.9.4"
serde_derive = "0.9.5"
rocket = "0.1.6"
rocket_codegen = "0.1.6"
yup-oauth2 = {version = "1.0.4"}
handlebars = {version = "0.24.1", features = ["serde_type"]}
lazy_static = "0.2.2"
chrono = {version = "0.2.25", features = ["serde"]}
dotenv = "0.8.0"
diesel = {version = "0.10.0", features = ["sqlite"]}
diesel_codegen = {version = "0.10.0", features = ["sqlite"]}
flate2 = {version = "0.2.17", features = []}
reqwest = "0.4.0"