[package]
name = "subscriptemember"
version = "0.5.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[features]
default = []

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
chrono-tz = "0.4"
clippy = {version = "0.0", optional = true}
diesel = {version = "0.16", features = ["sqlite"]}
diesel_codegen = {version = "0.16", features = ["sqlite"]}
dotenv = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = {version = "0.3", features = ["handlebars_templates", "json"]}
hyper = "0.11"
hyper-rustls = "0.11"
tokio-core = "0.1"
handlebars = "0.29"
r2d2 = "0.7"
r2d2-diesel = {version = "0.16"}
reqwest = "0.8"
nom = "3.0"
uuid = {version = "0.5", features = ["v4"]}
rayon = "0.8"
yup-oauth2 =  { git = "https://github.com/Narfinger/yup-oauth2"} 
#yup-oauth2 = {version = "1.0"}
ws = "0.7.3"         # Lightweight, event-driven WebSockets for Rust.


